import { MigrationInterface, QueryRunner } from 'typeorm';

export class InitialMigration1700000000000 implements MigrationInterface {
  name = 'InitialMigration1700000000000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    // This migration will be auto-generated by TypeORM
    // when you run: pnpm run db:migrate:generate
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    // This will be auto-generated as well
  }
}
