version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: news-backend-postgres
    environment:
      POSTGRES_DB: news_backend
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./pg-init-scripts:/docker-entrypoint-initdb.d
    networks:
      - news-backend-network

  redis:
    image: redis:7-alpine
    container_name: news-backend-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - news-backend-network

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: news-backend-app
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/news_backend
      REDIS_URL: redis://redis:6379
    ports:
      - "3000:3000"
      - "9090:9090"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres
      - redis
    networks:
      - news-backend-network
    command: npm run start:dev

volumes:
  postgres_data:
  redis_data:


networks:
  news-backend-network:
    driver: bridge
